import type { TemplateAnalysis, PreflightItem, BrandColor, AssetItem } from './types';

export const mockTemplateAnalysis: TemplateAnalysis = {
  fileName: 'BVRG-Pouch-250ml-V2.3.pdf',
  fileType: 'PDF',
  fileSize: '2.4 MB',
  manufacturer: 'PacPrint Industries Ltd',
  version: '2.3',
  analysedAt: new Date().toISOString(),
  dimensions: { width: 150, height: 210, unit: 'mm' },
  bleed: { top: 3, right: 3, bottom: 3, left: 3, unit: 'mm' },
  safeZone: { top: 5, right: 5, bottom: 5, left: 5, unit: 'mm' },
  colorMode: 'CMYK',
  resolution: '300 DPI minimum (600 DPI recommended for fine text)',
  cmykProfile: 'ISO Coated v2 300% (ECI)',
  pantoneRequirements: ['PANTONE 485 C', 'PANTONE 877 C (Silver)'],
  detectedElements: [
    'Trim line (red)',
    'Bleed boundary (magenta)',
    'Safe zone (green dashed)',
    'Fold lines × 2',
    'Barcode zone (back panel, lower right)',
    'White ink layer',
    'Silver foil zone (front panel top)',
    'Tear notch (top right corner)',
    'Hang hole (top centre)',
  ],
  layers: [
    { id: 'l1', name: 'Dieline', type: 'dieline', color: '#FF3B30', locked: true, visible: true },
    { id: 'l2', name: 'Bleed Area', type: 'bleed', color: '#FF6B35', locked: true, visible: true },
    { id: 'l3', name: 'Safe Zone', type: 'safe_zone', color: '#34C759', locked: true, visible: true },
    { id: 'l4', name: 'Fold Lines', type: 'fold_line', color: '#5B7FFF', locked: true, visible: true },
    { id: 'l5', name: 'White Ink', type: 'white_ink', color: '#FFFFFF', locked: false, visible: true },
    { id: 'l6', name: 'PANTONE 485 C', type: 'spot_color', color: '#DA291C', locked: false, visible: true },
    { id: 'l7', name: 'PANTONE 877 C', type: 'spot_color', color: '#9D9EA0', locked: false, visible: true },
    { id: 'l8', name: 'Varnish (Gloss)', type: 'varnish', color: '#E8E8E800', locked: false, visible: true },
    { id: 'l9', name: 'Barcode Zone', type: 'barcode_zone', color: '#0055FF', locked: true, visible: true },
    { id: 'l10', name: 'Notes / Annotations', type: 'notes', color: '#888888', locked: true, visible: true },
  ],
  instructions: [
    {
      id: 'i01',
      text: 'ALL artwork must be CMYK only. No RGB, LAB or indexed colours anywhere in the file.',
      priority: 'critical',
      category: 'colour',
      acknowledged: false,
    },
    {
      id: 'i02',
      text: 'Bleed must extend exactly 3 mm beyond the trim edge on all four sides. Bleed layer must not be deleted.',
      priority: 'critical',
      category: 'bleed',
      acknowledged: false,
    },
    {
      id: 'i03',
      text: 'All live text and logos must remain entirely within the safe zone (5 mm inside trim). Critical content such as barcodes, legal text and nutritional info must be at least 8 mm from trim.',
      priority: 'critical',
      category: 'text',
      acknowledged: false,
    },
    {
      id: 'i04',
      text: 'Barcode: EAN-13 format, minimum width 32 mm, height 22 mm, 5 mm quiet zone each side. Place within barcode zone on back panel only. Background must be white or very light.',
      priority: 'critical',
      category: 'barcode',
      acknowledged: false,
    },
    {
      id: 'i05',
      text: 'Silver foil area (top 35 mm of front panel) must use spot colour named exactly "PANTONE 877 C" — no variation in naming. Do not simulate with CMYK.',
      priority: 'critical',
      category: 'colour',
      acknowledged: false,
    },
    {
      id: 'i06',
      text: 'Primary brand colour must use spot colour named exactly "PANTONE 485 C". Convert all instances before supply.',
      priority: 'critical',
      category: 'colour',
      acknowledged: false,
    },
    {
      id: 'i07',
      text: 'Nutritional information panel is mandatory on the back panel. Minimum font size 7 pt. Must follow local food-labelling regulations.',
      priority: 'critical',
      category: 'legal',
      acknowledged: false,
    },
    {
      id: 'i08',
      text: 'All fonts must be outlined/converted to paths, OR the font files must be embedded. No live unembedded fonts in the final PDF.',
      priority: 'high',
      category: 'text',
      acknowledged: false,
    },
    {
      id: 'i09',
      text: 'All raster/bitmap images must be minimum 300 DPI at final print size. Images below 200 DPI will be rejected.',
      priority: 'high',
      category: 'resolution',
      acknowledged: false,
    },
    {
      id: 'i10',
      text: 'Do NOT place any artwork or text within 4 mm of the tear notch area (top-right corner, 8×8 mm). This area is structurally cut.',
      priority: 'high',
      category: 'dieline',
      acknowledged: false,
    },
    {
      id: 'i11',
      text: 'Hang hole area (top-centre, 5 mm diameter) must remain clear. No ink within 2 mm of the hang hole edge.',
      priority: 'high',
      category: 'dieline',
      acknowledged: false,
    },
    {
      id: 'i12',
      text: 'Recycling logo (minimum 15 mm diameter) required in bottom-right area of back panel. Must be the approved Australasian Recycling Label (ARL) mark.',
      priority: 'high',
      category: 'legal',
      acknowledged: false,
    },
    {
      id: 'i13',
      text: 'Country of origin statement must appear above or immediately adjacent to the barcode. Minimum 8 pt.',
      priority: 'high',
      category: 'legal',
      acknowledged: false,
    },
    {
      id: 'i14',
      text: 'The Dieline layer must be preserved as a separate layer in the final PDF, named exactly "Dieline". Do not flatten or merge it with artwork layers.',
      priority: 'high',
      category: 'dieline',
      acknowledged: false,
    },
    {
      id: 'i15',
      text: 'White ink: Where white is required on coloured/foil backgrounds, add artwork to the "White Ink" layer. White ink prints separately — do not rely on paper white.',
      priority: 'medium',
      category: 'colour',
      acknowledged: false,
    },
    {
      id: 'i16',
      text: 'Minimum text size anywhere on label: 6 pt. Legal/allergen declarations: minimum 7 pt.',
      priority: 'medium',
      category: 'text',
      acknowledged: false,
    },
    {
      id: 'i17',
      text: 'Allergen information must be clearly differentiated (bold, different colour, or highlighted) from surrounding ingredient text.',
      priority: 'medium',
      category: 'legal',
      acknowledged: false,
    },
    {
      id: 'i18',
      text: 'Total ink coverage must not exceed 300% (ISO Coated v2 profile). Use the supplied ICC profile for soft-proofing.',
      priority: 'medium',
      category: 'colour',
      acknowledged: false,
    },
    {
      id: 'i19',
      text: 'Gloss varnish will be applied to the entire front panel. Ensure no matte/satin varnish zones conflict with the Varnish layer.',
      priority: 'low',
      category: 'structure',
      acknowledged: false,
    },
    {
      id: 'i20',
      text: 'Supply artwork as a single multi-layer PDF/X-4 file. Do not supply flattened files or separate layers as individual files.',
      priority: 'low',
      category: 'structure',
      acknowledged: false,
    },
  ],
  manufacturerNotes:
    'Template v2.3 — Updated March 2024. Replaces v2.1. Changes: Silver foil zone expanded by 5mm, hang hole relocated to centre. For technical queries contact prepress@pacprint.co.nz or call 09-555-0198 (Mon–Fri 8am–4pm NZT). Proof approval required before print run commences.',
};

export const mockPreflightItems: PreflightItem[] = [
  { id: 'pf01', category: 'Dimensions', label: 'Page dimensions', status: 'pass', message: '150 × 210 mm — matches template', fixable: false },
  { id: 'pf02', category: 'Bleed', label: 'Bleed present', status: 'pass', message: '3 mm bleed on all sides', fixable: false },
  { id: 'pf03', category: 'Bleed', label: 'Artwork extends to bleed', status: 'warning', message: 'Background colour does not reach bleed edge on right side', detail: 'Extend background 3mm further right to fill bleed area.', fixable: true },
  { id: 'pf04', category: 'Safe Zone', label: 'Text inside safe zone', status: 'pass', message: 'All text objects are within the safe zone', fixable: false },
  { id: 'pf05', category: 'Safe Zone', label: 'Logos inside safe zone', status: 'warning', message: '1 image object is partially outside the safe zone', detail: 'The logo on the front panel overlaps the safe zone boundary by 2 px.', fixable: true },
  { id: 'pf06', category: 'Colour', label: 'Colour mode', status: 'warning', message: '2 objects use RGB colour values', detail: 'Objects #img-03 and #rect-07 are RGB. Convert to CMYK before export.', fixable: true },
  { id: 'pf07', category: 'Colour', label: 'PANTONE 485 C present', status: 'pass', message: 'Spot colour PANTONE 485 C found and correctly named', fixable: false },
  { id: 'pf08', category: 'Colour', label: 'PANTONE 877 C present', status: 'fail', message: 'Required spot colour PANTONE 877 C is missing', detail: 'Silver foil zone on front panel requires this exact spot colour. Add it or the file will be rejected.', fixable: true },
  { id: 'pf09', category: 'Colour', label: 'Ink density ≤ 300%', status: 'pass', message: 'Maximum ink density 248% — within spec', fixable: false },
  { id: 'pf10', category: 'Typography', label: 'Fonts outlined/embedded', status: 'warning', message: '3 text objects use live fonts that are not embedded', detail: '"Inter", "Inter Bold" are not embedded. Outline all text or embed fonts before export.', fixable: true },
  { id: 'pf11', category: 'Typography', label: 'Minimum font size', status: 'pass', message: 'All text is 6 pt or larger', fixable: false },
  { id: 'pf12', category: 'Images', label: 'Image resolution', status: 'warning', message: '1 raster image below 300 DPI at final size', detail: '"product-photo.jpg" is 187 DPI. Replace with higher-resolution version.', fixable: false },
  { id: 'pf13', category: 'Barcode', label: 'Barcode present', status: 'pass', message: 'EAN-13 barcode found in barcode zone', fixable: false },
  { id: 'pf14', category: 'Barcode', label: 'Barcode quiet zone', status: 'pass', message: '5.2 mm quiet zone — meets 5 mm minimum', fixable: false },
  { id: 'pf15', category: 'Dieline', label: 'Dieline layer preserved', status: 'pass', message: 'Dieline layer present and locked', fixable: false },
  { id: 'pf16', category: 'Dieline', label: 'Tear notch clear', status: 'pass', message: 'No artwork within tear notch exclusion zone', fixable: false },
  { id: 'pf17', category: 'Legal', label: 'Nutrition panel', status: 'info', message: 'Nutrition panel detected — verify content is accurate before export', detail: 'The app cannot validate nutritional values. Please confirm all values with your nutritionist.', fixable: false },
  { id: 'pf18', category: 'Legal', label: 'Recycling mark', status: 'warning', message: 'No ARL recycling mark detected', detail: 'Add an Australasian Recycling Label (ARL) to the back panel before submitting.', fixable: false },
  { id: 'pf19', category: 'Legal', label: 'Country of origin', status: 'pass', message: '"Made in New Zealand" text found adjacent to barcode', fixable: false },
  { id: 'pf20', category: 'Structure', label: 'Instructions acknowledged', status: 'warning', message: '3 template instructions have not been acknowledged', detail: 'Complete the instruction checklist in the Analyze step.', fixable: false },
];

export const mockBrandColors: BrandColor[] = [
  { id: 'bc1', name: 'Brand Red', hex: '#DA291C', pantone: 'PANTONE 485 C', cmyk: { c: 0, m: 95, y: 100, k: 0 } },
  { id: 'bc2', name: 'Silver Foil', hex: '#9D9EA0', pantone: 'PANTONE 877 C', cmyk: { c: 0, m: 0, y: 0, k: 40 } },
  { id: 'bc3', name: 'Deep Navy', hex: '#0A1628', cmyk: { c: 95, m: 80, y: 40, k: 35 } },
  { id: 'bc4', name: 'Pure White', hex: '#FFFFFF', cmyk: { c: 0, m: 0, y: 0, k: 0 } },
  { id: 'bc5', name: 'Rich Black', hex: '#0C0C0C', cmyk: { c: 60, m: 40, y: 40, k: 100 } },
  { id: 'bc6', name: 'Citrus Gold', hex: '#F5A623', cmyk: { c: 0, m: 35, y: 90, k: 0 } },
];

export const mockAssets: AssetItem[] = [
  {
    id: 'a01', name: 'Lemon', category: 'Fruit',
    thumbnail: 'lemon',
    svgContent: `<svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg"><ellipse cx="32" cy="32" rx="28" ry="22" fill="#FFE034"/><ellipse cx="32" cy="32" rx="22" ry="16" fill="#FFD116"/><path d="M32 10 Q36 16 36 32 Q36 48 32 54 Q28 48 28 32 Q28 16 32 10Z" fill="#FFBE00" opacity="0.4"/><ellipse cx="10" cy="32" rx="4" ry="6" fill="#FFE034"/><ellipse cx="54" cy="32" rx="4" ry="6" fill="#FFE034"/></svg>`,
  },
  {
    id: 'a02', name: 'Lime', category: 'Fruit',
    thumbnail: 'lime',
    svgContent: `<svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg"><circle cx="32" cy="32" r="28" fill="#5CB85C"/><circle cx="32" cy="32" r="22" fill="#4CAF50"/><path d="M32 8 Q36 16 36 32 Q36 48 32 56 Q28 48 28 32 Q28 16 32 8Z" fill="#388E3C" opacity="0.4"/></svg>`,
  },
  {
    id: 'a03', name: 'Raspberry', category: 'Fruit',
    thumbnail: 'raspberry',
    svgContent: `<svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg"><circle cx="26" cy="30" r="12" fill="#C41E3A"/><circle cx="38" cy="30" r="12" fill="#C41E3A"/><circle cx="32" cy="20" r="12" fill="#D62345"/><circle cx="32" cy="40" r="12" fill="#D62345"/><circle cx="26" cy="30" r="4" fill="#A01830" opacity="0.6"/><circle cx="38" cy="30" r="4" fill="#A01830" opacity="0.6"/><circle cx="32" cy="20" r="4" fill="#A01830" opacity="0.6"/><circle cx="32" cy="40" r="4" fill="#A01830" opacity="0.6"/><path d="M28 8 L32 12 L36 8 L34 4 L30 4Z" fill="#2D5A1B"/></svg>`,
  },
  {
    id: 'a04', name: 'Organic Badge', category: 'Claims',
    thumbnail: 'organic',
    svgContent: `<svg viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg"><polygon points="40,4 52,12 64,8 68,20 78,28 74,40 78,52 68,60 64,72 52,68 40,76 28,68 16,72 12,60 2,52 6,40 2,28 12,20 16,8 28,12" fill="#2E7D32" stroke="#1B5E20" stroke-width="1.5"/><text x="40" y="34" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="bold" fill="white">CERTIFIED</text><text x="40" y="46" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="bold" fill="white">ORGANIC</text></svg>`,
  },
  {
    id: 'a05', name: 'Non-GMO', category: 'Claims',
    thumbnail: 'nongmo',
    svgContent: `<svg viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg"><circle cx="40" cy="40" r="36" fill="none" stroke="#388E3C" stroke-width="3"/><text x="40" y="34" text-anchor="middle" font-family="sans-serif" font-size="8" font-weight="bold" fill="#388E3C">NON</text><text x="40" y="44" text-anchor="middle" font-family="sans-serif" font-size="8" font-weight="bold" fill="#388E3C">GMO</text><path d="M16 62 Q40 52 64 62" fill="none" stroke="#388E3C" stroke-width="2"/></svg>`,
  },
  {
    id: 'a06', name: 'Gluten Free', category: 'Claims',
    thumbnail: 'glutenfree',
    svgContent: `<svg viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg"><rect x="4" y="4" width="72" height="72" rx="8" fill="#F57C00" stroke="#E65100" stroke-width="1.5"/><text x="40" y="30" text-anchor="middle" font-family="sans-serif" font-size="7" font-weight="bold" fill="white">GLUTEN</text><text x="40" y="42" text-anchor="middle" font-family="sans-serif" font-size="7" font-weight="bold" fill="white">FREE</text><line x1="12" y1="52" x2="68" y2="52" stroke="white" stroke-width="1.5" opacity="0.5"/><text x="40" y="62" text-anchor="middle" font-family="sans-serif" font-size="6" fill="white">CERTIFIED</text></svg>`,
  },
  {
    id: 'a07', name: 'Wave Pattern', category: 'Decorative',
    thumbnail: 'wave',
    svgContent: `<svg viewBox="0 0 200 40" xmlns="http://www.w3.org/2000/svg"><path d="M0 20 C20 5, 40 35, 60 20 S100 5, 120 20 S160 35, 180 20 S200 5, 200 20" fill="none" stroke="#5B7FFF" stroke-width="3"/><path d="M0 28 C20 13, 40 43, 60 28 S100 13, 120 28 S160 43, 180 28 S200 13, 200 28" fill="none" stroke="#5B7FFF" stroke-width="2" opacity="0.5"/></svg>`,
  },
  {
    id: 'a08', name: 'Burst', category: 'Decorative',
    thumbnail: 'burst',
    svgContent: `<svg viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg"><polygon points="40,2 44,30 72,20 52,42 78,54 48,52 50,80 40,58 30,80 32,52 2,54 28,42 8,20 36,30" fill="#FFB347"/></svg>`,
  },
];
